#!/usr/bin/env bash
# This script installs nginx on web-01 server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
#sudo /etc/init.d/nginx restart
#sudo rm /var/www/html/*.html
#sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo service nginx restart
