#!/usr/bin/env bash
# This script installs nginx on web-01 server

sudo apt-get -y update
sudo apt-get install -y nginx
#sudo ufw allow 'Nginx HTTP'
#sudo /etc/init.d/nginx restart
#sudo rm /var/www/html/*.html
sudo service nginx restart
sudo echo "Hello World" | sudo tee /var/www/html/index.html
#sudo sh -c 'echo "Hello World" > /var/www/html/index.html'

#sudo sed -i 's/listen\s*80;/listen 80 defualt_server;/g' /etc/nginx/sites-available/default
#sudo sed -i 's|#*root /var/www/html;|root /var/www/html;|g' /etc/nginx/sites-available/default
#sudo sed -i 's|#*index index.html;|index index.html;|g' /etc/nginx/sites-available/default

